import { useState, useEffect } from 'react'
import { useSupabaseClient } from '@supabase/auth-helpers-react'
import md from 'markdown-it'
import Layout from '../../../components/Layout.js'

export default function Contact({ id }) {
  const [contact, setContact] = useState(null)
  const supabase = useSupabaseClient()

  useEffect(() => {
    const fetchContact = async () => {
      let { data, error, status } = await supabase
        .from('contacts')
        .select(`firstname, lastname, email, message`)
        .eq('id', id)
        .single()
      setContact(data)
    };

    fetchContact();
  }, [id, supabase])

  return (
    <Layout title="Admin Contacts" description="Generated by create next app">
      <h1 className="text-3xl font-semibold text-blue-600 mb-4">View a Contact Message</h1>
      {contact && (
        <div className="bg-white shadow-md overflow-hidden sm:rounded-lg">
          <div className="bg-gray-50 px-4 py-5 border-b border-gray-200 sm:px-6">
            <dl className="grid grid-cols-[auto_1fr] gap-x-4 gap-y-8 sm:grid-cols-2">
              <div className="sm:col-span-1">
                <dt className="text-sm font-medium text-gray-500">Name</dt>
                <dd className="mt-1 text-sm text-gray-900">{contact.lastname}, {contact.firstname}</dd>
              </div>
              <div className="sm:col-span-1">
                <dt className="text-sm font-medium text-gray-500">Email</dt>
                <dd className="mt-1 text-sm text-gray-900">{contact.email}</dd>
              </div>
            </dl>
          </div>
          <div className="px-4 py-5 sm:p-6">
            <h3 className="text-lg leading-6 font-medium text-gray-900">Message</h3>
            <div
              className="mt-2 max-w-xl text-sm text-gray-500"
              dangerouslySetInnerHTML={{ __html: md().render(contact.message) }}
            />
          </div>
        </div>
      )}
    </Layout>
  );
}

export async function getServerSideProps(context) {
  return {
    props: {
      id: context.params.id
    },
  };
}
